In [2]:
# Phạm Thành Long B22DCCN505
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
x = tf.placeholder(tf.float32,[2,4,3])
y = tf.placeholder(tf.float32,[2,4,3])
z = tf.add(x,y)
u = tf.multiply(x,y)
with tf.Session() as sess:
 x_data= [[[1,2,3],
 [2,3,4],
 [2,3,5],
 [0,1,2]
 ],
 [[1,2,3],
 [2,3,4],
 [2,3,5],
 [0,1,2]
 ]]
 y_data= [[[1,2,3],
 [2,3,4],
 [2,3,5],
 [0,1,2]
 ],
 [[1,2,3],
 [2,3,4],
 [2,3,5],
 [0,1,2]
 ]]
 result1 = sess.run(z,feed_dict={x:x_data, y:y_data})
 result2 = sess.run(u,feed_dict={x:x_data, y:y_data})
 print("result1 =", result1)
 print("result2 =", result2)


result1 = [[[ 2.  4.  6.]
  [ 4.  6.  8.]
  [ 4.  6. 10.]
  [ 0.  2.  4.]]

 [[ 2.  4.  6.]
  [ 4.  6.  8.]
  [ 4.  6. 10.]
  [ 0.  2.  4.]]]
result2 = [[[ 1.  4.  9.]
  [ 4.  9. 16.]
  [ 4.  9. 25.]
  [ 0.  1.  4.]]

 [[ 1.  4.  9.]
  [ 4.  9. 16.]
  [ 4.  9. 25.]
  [ 0.  1.  4.]]]
