In [2]:
# Phạm Thành Long B22DCCN505
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
x = tf.placeholder(tf.float32,[None,4,3])
y = tf.add(x,x)
with tf.Session() as sess:
 x_data= [[[1,2,3],
 [2,3,4],
 [2,3,5],
 [0,1,2]
 ]]
 result = sess.run(y,feed_dict={x:x_data})
 print(result)


[[[ 2.  4.  6.]
  [ 4.  6.  8.]
  [ 4.  6. 10.]
  [ 0.  2.  4.]]]
